### ISSUE TITLE
http://127.0.0.1:8000/mine

### ISSUE THREAD

**Issue by deepaksh2007** [satwikkansal/python_blockchain_app#36]
While mining I am getting the issue. May I know where I am going wrong.

http://127.0.0.1:8000/mine

Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by ptr-r-thompson** [comment]
Be sure you have started node_server.py on the node (127.0.0.1:8000).  It is critical in your command shell that the command:
>set FLASK_APP=node_server.py
is issued and then the:
>flask run --port 8000
command.  I am using windows, so "set" is used instead of the "export" for Linux (or perhaps others).  This needs to be done in a separate command shell (cmd from the run command line in windows.

At this point you should be able to navigate to http://127.0.0.1:8000/mine in your browser and see the contents (likely to be "There are no transactions to mine." unless you are using the app to request mining.

BTW, if you follow the tutorial and spin up new nodes (on 127.0.0.1:8001 for example) you MUST repeat the "set" command in the new command shell before issuing the "flask run" command.

Each run (any node_server runs and the app run) MUST be done in a separate cmd window.  When setting up and experimenting with this you will have a minimum of 2 cmd windows open (one for app, and one for node_server).  You can then navigate to the app (http://127.0.0.1:5000) and the node server (http://127.0.0.1:8000/mine) in your browser to see the screenshots shown in the tutorial.

**Comment by satwikkansal** [comment]
Exactly what @ptr-r-thompson said (thanks).

Closing this issue, feel free to open if the problem persists.
